#nullable enable
namespace FlowerBI.DemoSchema;


// Important: this file is auto-generated by flowerbi.

public static class BugSchema
{
    public const string Name = "BugSchema";
    public static class Date
    {
        public const string Name = "Date";
        public const string Id = "Date.Id";
        public const string CalendarYearNumber = "Date.CalendarYearNumber";
        public const string FirstDayOfQuarter = "Date.FirstDayOfQuarter";
        public const string FirstDayOfMonth = "Date.FirstDayOfMonth";
    }
    public static class DateReported
    {
        public const string Name = "DateReported";
        public const string Id = "DateReported.Id";
        public const string CalendarYearNumber = "DateReported.CalendarYearNumber";
        public const string FirstDayOfQuarter = "DateReported.FirstDayOfQuarter";
        public const string FirstDayOfMonth = "DateReported.FirstDayOfMonth";
    }
    public static class DateResolved
    {
        public const string Name = "DateResolved";
        public const string Id = "DateResolved.Id";
        public const string CalendarYearNumber = "DateResolved.CalendarYearNumber";
        public const string FirstDayOfQuarter = "DateResolved.FirstDayOfQuarter";
        public const string FirstDayOfMonth = "DateResolved.FirstDayOfMonth";
    }
    public static class DateAssigned
    {
        public const string Name = "DateAssigned";
        public const string Id = "DateAssigned.Id";
        public const string CalendarYearNumber = "DateAssigned.CalendarYearNumber";
        public const string FirstDayOfQuarter = "DateAssigned.FirstDayOfQuarter";
        public const string FirstDayOfMonth = "DateAssigned.FirstDayOfMonth";
    }
    public static class Workflow
    {
        public const string Name = "Workflow";
        public const string Id = "Workflow.Id";
        public const string Resolved = "Workflow.Resolved";
        public const string WorkflowState = "Workflow.WorkflowState";
        public const string SourceOfError = "Workflow.SourceOfError";
        public const string FixedByCustomer = "Workflow.FixedByCustomer";
    }
    public static class Category
    {
        public const string Name = "Category";
        public const string Id = "Category.Id";
        public const string Label = "Category.Label";
    }
    public static class Customer
    {
        public const string Name = "Customer";
        public const string Id = "Customer.Id";
        public const string CustomerName = "Customer.CustomerName";
    }
    public static class Coder
    {
        public const string Name = "Coder";
        public const string Id = "Coder.Id";
        public const string FullName = "Coder.FullName";
    }
    public static class CoderAssigned
    {
        public const string Name = "CoderAssigned";
        public const string Id = "CoderAssigned.Id";
        public const string FullName = "CoderAssigned.FullName";
    }
    public static class CoderResolved
    {
        public const string Name = "CoderResolved";
        public const string Id = "CoderResolved.Id";
        public const string FullName = "CoderResolved.FullName";
    }
    public static class CategoryCombination
    {
        public const string Name = "CategoryCombination";
        public const string Id = "CategoryCombination.Id";
        public const string Crashed = "CategoryCombination.Crashed";
        public const string DataLoss = "CategoryCombination.DataLoss";
        public const string SecurityBreach = "CategoryCombination.SecurityBreach";
        public const string OffByOne = "CategoryCombination.OffByOne";
        public const string Slow = "CategoryCombination.Slow";
        public const string StackOverflow = "CategoryCombination.StackOverflow";
    }
    public static class Bug
    {
        public const string Name = "Bug";
        public const string Id = "Bug.Id";
        public const string WorkflowId = "Bug.WorkflowId";
        public const string CustomerId = "Bug.CustomerId";
        public const string ReportedDate = "Bug.ReportedDate";
        public const string ResolvedDate = "Bug.ResolvedDate";
        public const string AssignedDate = "Bug.AssignedDate";
        public const string CategoryCombinationId = "Bug.CategoryCombinationId";
        public const string AssignedCoderId = "Bug.AssignedCoderId";
        public const string ResolvedCoderId = "Bug.ResolvedCoderId";
    }
    
    public const string Yaml = """
        schema: BugSchema
        name: main
        tables:
            Date:
                id:
                    Id: [datetime]
                columns:
                    CalendarYearNumber: [short]
                    FirstDayOfQuarter: [datetime]
                    FirstDayOfMonth: [datetime]
        
            DateReported:
                extends: Date
        
            DateResolved:
                extends: Date
        
            DateAssigned:
                extends: Date
        
            Workflow:
                id:
                    Id: [int]
                columns:
                    Resolved: [bool]
                    WorkflowState: [string]
                    SourceOfError: [string]
                    FixedByCustomer: [bool]
        
            Category:
                id:
                    Id: [int]
                columns:
                    Label: [string]
        
            Customer:
                id:
                    Id: [int]
                columns:
                    CustomerName: [string]
        
            Coder:
                id:
                    Id: [int]
                columns:
                    FullName: [string]
        
            CoderAssigned:
                extends: Coder
        
            CoderResolved:
                extends: Coder
        
            CategoryCombination:
                id:
                    Id: [int]
                columns:
                    Crashed: [bool]
                    DataLoss: [bool]
                    SecurityBreach: [bool]
                    OffByOne: [bool]
                    Slow: [bool]
                    StackOverflow: [bool]
        
            Bug:
                id:
                    Id: [int]
                columns:
                    WorkflowId: [Workflow]
                    CustomerId: [Customer]
                    ReportedDate: [DateReported]
                    ResolvedDate: [DateResolved]
                    AssignedDate: [DateAssigned]
                    CategoryCombinationId: [CategoryCombination]
                    AssignedCoderId: [CoderAssigned]
                    ResolvedCoderId: [CoderResolved]
        
        """;
}
