using System.IO;
using FlowerBI.Yaml;

namespace FlowerBI.Conversion;

public static class CSharp
{
    public static void FromYaml(
        string yamlFile,
        string csFile,
        string csNamespace,
        TextWriter console
    )
    {
        var yamlContent = File.ReadAllText(yamlFile);
        var schema = ResolvedSchema.Resolve(yamlContent);

        using var writer = new WriteIfDifferent(csFile, console);
        FromSchema(schema, yamlContent, writer.Output, csNamespace, writer.Console);
    }

    public static void FromSchema(
        ResolvedSchema schema,
        string yamlContent,
        TextWriter writer,
        string csNamespace,
        TextWriter console
    )
    {
        writer.WriteLine($"namespace {csNamespace};");
        writer.WriteLine();
        writer.WriteLine("using FlowerBI;");
        writer.WriteLine();
        writer.WriteLine("// Important: this file is auto-generated by flowerbi.");
        writer.WriteLine();
        writer.WriteLine($"public static class {schema.Name}");
        writer.WriteLine("{");

        var schemaWriter = new IndentedWriter(writer);

        // Generate table classes with string constants
        foreach (var table in schema.Tables)
        {
            console.WriteLine($"Exporting table {table.Name}");

            schemaWriter.WriteLine($"public static class {table.Name}");
            schemaWriter.WriteLine("{");

            var tableWriter = new IndentedWriter(schemaWriter);

            // Write ID column if present
            if (table.IdColumn != null)
            {
                tableWriter.WriteLine(
                    $"public const string {table.IdColumn.Name} = \"{table.Name}.{table.IdColumn.Name}\";"
                );
            }

            // Write regular columns
            foreach (var column in table.Columns)
            {
                tableWriter.WriteLine(
                    $"public const string {column.Name} = \"{table.Name}.{column.Name}\";"
                );
            }

            schemaWriter.WriteLine("}");
            schemaWriter.WriteLine();
        }

        // Embed YAML as triple-quoted string
        schemaWriter.WriteLine("private const string YamlSchema = \"\"\"");

        // Write YAML content with proper indentation
        var yamlWriter = new IndentedWriter(schemaWriter);
        foreach (var line in yamlContent.Replace("\r\n", "\n").Split('\n'))
        {
            yamlWriter.WriteLine(line);
        }

        schemaWriter.WriteLine("\"\"\";");
        schemaWriter.WriteLine();

        // Generate static Schema property
        schemaWriter.WriteLine(
            $"public static Schema Schema {{ get; }} = FlowerBI.Schema.FromYaml(YamlSchema);"
        );

        writer.WriteLine("}");

        writer.Flush();
        console.WriteLine("Done.");
    }
}
