using System;
using System.IO;
using FlowerBI.Yaml;

namespace FlowerBI.Conversion;

public static class CSharp
{
    static string CSColumnType(DataType dataType, bool nullable)
    {
        var csType = dataType switch
        {
            DataType.Bool => "bool",
            DataType.Byte => "byte",
            DataType.Short => "short",
            DataType.Int => "int",
            DataType.Long => "long",
            DataType.Float => "float",
            DataType.Double => "double",
            DataType.Decimal => "decimal",
            DataType.String => "string",
            DataType.DateTime => "DateTime",
            _ => throw new InvalidOperationException($"Unsupported data type: {dataType}")
        };

        return nullable ? $"{csType}?" : csType;
    }

    public static void FromYaml(string yamlFile, string csFile, string csNamespace, TextWriter console)
        => FromSchema(ResolvedSchema.Resolve(File.ReadAllText(yamlFile)), csFile, csNamespace, console);

    static void FromSchema(ResolvedSchema schema, string csFile, string csNamespace, TextWriter console)
    {
        using var writer = new StreamWriter(csFile);

        console.WriteLine($"Saving to file {csFile}");
        FromSchema(schema, writer, csNamespace, console);
    }

    public static void FromSchema(ResolvedSchema schema, TextWriter writer, string csNamespace, TextWriter console)
    {            
        writer.WriteLine("#nullable enable");
        writer.WriteLine($"namespace {csNamespace};");
        writer.WriteLine("using System;");
        writer.WriteLine("using FlowerBI;");
        writer.WriteLine();
        writer.WriteLine();
        writer.WriteLine("// Important: this file is auto-generated by flowerbi.");
        writer.WriteLine();
        
        writer.WriteLine($"[DbSchema(\"{schema.NameInDb}\")]");
        writer.WriteLine($"public static class {schema.Name}");
        writer.WriteLine("{");

        var schemaWriter = new IndentedWriter(writer);

        foreach (var table in schema.Tables)
        {
            console.WriteLine($"Exporting table {table.Name}");

            schemaWriter.WriteLine($"[DbTable(\"{table.NameInDb}\")]");
            schemaWriter.WriteLine($"public static class {table.Name}");
            schemaWriter.WriteLine("{");

            string ExtendColumn(ResolvedColumn c) => c.Extends == null 
                ? string.Empty 
                : $", extends: {c.Extends.Table.Name}.{c.Extends.Name}";

            var tableWriter = new IndentedWriter(schemaWriter);

            if (table.IdColumn != null)
            {
                var idType = CSColumnType(table.IdColumn.DataType, table.IdColumn.Nullable);

                tableWriter.WriteLine($"public static readonly PrimaryKey<{idType}> {table.IdColumn.Name} = new PrimaryKey<{idType}>(\"{table.IdColumn.Name}\"{ExtendColumn(table.IdColumn)});");
            }

            foreach (var column in table.Columns)
            {
                var columnType = CSColumnType(column.DataType, column.Nullable);

                if (column.Target != null)
                {
                    tableWriter.WriteLine($"public static readonly ForeignKey<{columnType}> {column.Name} = new ForeignKey<{columnType}>(\"{column.Name}\", {column.Target.Table.Name}.{column.Target.Name}{ExtendColumn(column)});");
                }
                else
                {
                    tableWriter.WriteLine($"public static readonly Column<{columnType}> {column.Name} = new Column<{columnType}>(\"{column.Name}\"{ExtendColumn(column)});");
                }
            }    

            schemaWriter.WriteLine("}");
        }

        writer.WriteLine("}");
        
        writer.Flush();
        console.WriteLine("Done.");
    }
}
