using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using FlowerBI.Yaml;

namespace FlowerBI.Conversion;

public static class TypeScript
{
    static (string Decl, string Cls) TSColumnType(DataType dataType, bool nullable)
    {
        var jsType = dataType switch
        {
            DataType.Bool => "boolean",
            DataType.String => "string",
            DataType.DateTime => "Date",
            _ => "number",
        };
        if (nullable)
        {
            jsType = $"{jsType} | null";
        }

        return jsType == "string" ? ($"StringQueryColumn<{jsType}>", "StringQueryColumn")
            : jsType != "number" ? ($"QueryColumn<{jsType}>", "QueryColumn")
            : dataType is DataType.Decimal or DataType.Float or DataType.Double
                ? ($"NumericQueryColumn<{jsType}>", "NumericQueryColumn")
            : ($"IntegerQueryColumn<{jsType}>", "IntegerQueryColumn");
    }

    public static void FromYaml(string yamlFile, string tsFile, TextWriter console) =>
        FromSchema(ResolvedSchema.Resolve(File.ReadAllText(yamlFile)), tsFile, console);

    static void FromSchema(ResolvedSchema schema, string tsFile, TextWriter console)
    {
        using var writer = new WriteIfDifferent(tsFile, console);

        FromSchema(schema, writer.Output, writer.Console);
    }

    public static void FromSchema(
        ResolvedSchema schema,
        TextWriter outputWriter,
        TextWriter console
    )
    {
        var imports = new HashSet<string>(["QueryColumnRuntimeType", "QueryColumnDataType"]);

        var writer = new StringWriter();

        writer.WriteLine("// Important: this file is auto-generated by flowerbi.");
        writer.WriteLine();

        var topicNames = new HashSet<string>(schema.Topics.Select(t => t.Name));

        var tableWriter = new IndentedWriter(writer);

        foreach (var table in schema.Tables)
        {
            console.WriteLine($"Exporting table {table.Name}");

            WriteJsDoc(writer, indent: "", table.Doc, table.See, topicNames);
            writer.WriteLine($"export const {table.Name} = {{");

            var idColumn =
                table.IdColumn != null
                    ? new[] { table.IdColumn }
                    : Enumerable.Empty<ResolvedColumn>();

            string GetTargetString(ResolvedColumn column) =>
                column == null ? "" : $"{column.Table.Name}.{column.Name}";

            foreach (var column in idColumn.Concat(table.Columns))
            {
                var (tsType, importType) = TSColumnType(column.DataType, column.Nullable);
                imports.Add(importType);

                WriteJsDoc(writer, indent: "    ", column.Doc, column.See, topicNames);

                // 8 spaces aligns the meta object with the other QueryColumnRuntimeType args.
                var metaArg =
                    column.Meta != null && column.Meta.Count > 0
                        ? $",\n        {TsMeta(column.Meta)}"
                        : "";

                tableWriter.WriteLine(
                    $"""
                    {column.Name}: new {tsType}("{table.Name}.{column.Name}",
                        new QueryColumnRuntimeType(
                            QueryColumnDataType.{column.DataType},
                            "{GetTargetString(column.Target)}"{metaArg}
                        )
                    ),
                    """
                );
            }

            if (table.Meta != null && table.Meta.Count > 0)
            {
                tableWriter.WriteLine($"$meta: {TsMeta(table.Meta)},");
            }

            writer.WriteLine("};");
            writer.WriteLine();
        }

        if (schema.Topics.Any())
        {
            console.WriteLine("Exporting topics");
            writer.WriteLine("export const Topics = {");
            foreach (var topic in schema.Topics)
            {
                WriteJsDoc(writer, indent: "    ", topic.Doc, topic.See, topicNames);
                tableWriter.WriteLine($"{TsKey(topic.Name)}: {TsString(topic.Name)},");
            }
            writer.WriteLine("};");
            writer.WriteLine();
        }

        writer.WriteLine($"export const {schema.Name} = {{");
        foreach (var table in schema.Tables)
        {
            tableWriter.WriteLine(@$"{table.Name},");
        }
        writer.WriteLine("};");

        writer.Flush();

        if (imports.Count != 0)
        {
            outputWriter.WriteLine(
                @$"import {{ {string.Join(", ", imports.OrderBy(x => x))} }} from ""flowerbi"";"
            );
            outputWriter.WriteLine();
        }

        outputWriter.Write(writer.ToString());

        outputWriter.Flush();

        console.WriteLine("Done.");
    }

    private static void WriteJsDoc(
        StringWriter writer,
        string indent,
        string doc,
        IReadOnlyList<string> see,
        HashSet<string> topicNames
    )
    {
        var hasDoc = !string.IsNullOrEmpty(doc);
        var hasSee = see != null && see.Count > 0;
        if (!hasDoc && !hasSee)
        {
            return;
        }

        writer.WriteLine($"{indent}/**");
        if (hasDoc)
        {
            foreach (var line in SplitLines(doc))
            {
                writer.WriteLine($"{indent} * {line}");
            }
        }
        if (hasSee)
        {
            foreach (var entry in see)
            {
                writer.WriteLine(
                    $"{indent} * @see {{@link {RewriteSeeForJsDoc(entry, topicNames)}}}"
                );
            }
        }
        writer.WriteLine($"{indent} */");
    }

    private static string RewriteSeeForJsDoc(string entry, HashSet<string> topicNames)
    {
        if (entry.Contains('.') || !topicNames.Contains(entry))
        {
            return entry;
        }
        return IsValidJsIdentifier(entry) ? $"Topics.{entry}" : $"Topics[{TsString(entry)}]";
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        var trimmed = text.Replace("\r\n", "\n").TrimEnd('\n');
        return trimmed.Split('\n');
    }

    private static bool IsValidJsIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return false;
        }
        if (!char.IsLetter(name[0]) && name[0] != '_' && name[0] != '$')
        {
            return false;
        }
        for (var i = 1; i < name.Length; i++)
        {
            var c = name[i];
            if (!char.IsLetterOrDigit(c) && c != '_' && c != '$')
            {
                return false;
            }
        }
        return true;
    }

    private static string TsMeta(IReadOnlyDictionary<string, string> meta)
    {
        var pairs = meta.Select(kvp => $"{TsString(kvp.Key)}: {TsString(kvp.Value)}");
        return $"{{ {string.Join(", ", pairs)} }}";
    }

    private static string TsKey(string name) => IsValidJsIdentifier(name) ? name : TsString(name);

    private static string TsString(string s) =>
        $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
