using System.Collections.Generic;
using System.IO;
using System.Linq;
using FlowerBI.Yaml;

namespace FlowerBI.Conversion;

public static class TypeScript
{
    static (string Decl, string Cls) TSColumnType(DataType dataType, bool nullable)
    {
        var jsType = dataType switch
        {
            DataType.Bool => "boolean",
            DataType.String => "string",
            DataType.DateTime => "Date",
            _ => "number"
        };
        if (nullable)
        {
            jsType = $"{jsType} | null";
        }

        return jsType != "number" ? ($"QueryColumn<{jsType}>", "QueryColumn") :
               dataType is DataType.Decimal or DataType.Float or DataType.Double ? ($"NumericQueryColumn<{jsType}>", "NumericQueryColumn") : 
               ($"IntegerQueryColumn<{jsType}>", "IntegerQueryColumn");
    }

    public static void FromYaml(string yamlFile, string tsFile, TextWriter console)
        => FromSchema(ResolvedSchema.Resolve(File.ReadAllText(yamlFile)), tsFile, console);
    
    public static void FromReflection(string path, string schemaClass, string tsFile, TextWriter console)
        => FromSchema(Reflection.ToSchema(path, schemaClass, console), tsFile, console);
    
    static void FromSchema(ResolvedSchema schema, string tsFile, TextWriter console)
    {
        using var writer = new StreamWriter(tsFile);

        console.WriteLine($"Saving to file {tsFile}");
        FromSchema(schema, writer, console);
    }

    public static void FromSchema(ResolvedSchema schema, TextWriter outputWriter, TextWriter console)
    {
        var imports = new HashSet<string>();

        var writer = new StringWriter();

        writer.WriteLine("// Important: this file is auto-generated by flowerbi.");
        writer.WriteLine();

        var tableWriter = new IndentedWriter(writer);

        foreach (var table in schema.Tables)
        {
            console.WriteLine($"Exporting table {table.Name}");
            writer.WriteLine($"export const {table.Name} = {{");

            var idColumn = table.IdColumn != null ? new[] { table.IdColumn } : Enumerable.Empty<ResolvedColumn>();

            foreach (var column in idColumn.Concat(table.Columns))
            {
                var (tsType, importType) = TSColumnType(column.DataType, column.Nullable);
                imports.Add(importType);

                tableWriter.WriteLine(@$"{column.Name}: new {tsType}(""{table.Name}.{column.Name}""),");
            }

            writer.WriteLine("};");
            writer.WriteLine();
        }
        
        writer.WriteLine($"export const {schema.Name} = {{");
        foreach (var table in schema.Tables)
        {
            tableWriter.WriteLine(@$"{table.Name},");
        }
        writer.WriteLine("};");

        writer.Flush();

        if (imports.Count != 0)
        {
            outputWriter.WriteLine(@$"import {{ {string.Join(", ", imports.OrderBy(x => x))} }} from ""flowerbi"";");
            outputWriter.WriteLine();
        }

        outputWriter.Write(writer.ToString());

        outputWriter.Flush();

        console.WriteLine("Done.");
    }
}
