namespace FlowerBI.Engine.Tests;

using System;
using System.IO;
using FlowerBI.Conversion;
using FlowerBI.Yaml;
using FluentAssertions;
using Xunit;

public class ConversionTests
{
    [Fact]
    public void GeneratesTypeScriptFromYaml()
    {
        var yaml = ExecutionTests.FindSchemaText("testSchema");

        var writer = new StringWriter();
        var console = new StringWriter();
        TypeScript.FromSchema(yaml, writer, console);

        writer
            .ToString()
            .Trim()
            .Should()
            .Be(
                """
import { IntegerQueryColumn, NumericQueryColumn, QueryColumn, QueryColumnDataType, QueryColumnRuntimeType, StringQueryColumn } from "@flowerbi/client";

// Important: this file is auto-generated by flowerbi.

export const Department = {
    Id: new IntegerQueryColumn<number>("Department.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    DepartmentName: new StringQueryColumn<string>("Department.DepartmentName",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
};

export const Vendor = {
    Id: new IntegerQueryColumn<number>("Vendor.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    VendorName: new StringQueryColumn<string>("Vendor.VendorName",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
    DepartmentId: new IntegerQueryColumn<number>("Vendor.DepartmentId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Department.Id"
    )
), 
};

export const Invoice = {
    Id: new IntegerQueryColumn<number>("Invoice.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    VendorId: new IntegerQueryColumn<number>("Invoice.VendorId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Vendor.Id"
    )
), 
    DepartmentId: new IntegerQueryColumn<number>("Invoice.DepartmentId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Department.Id"
    )
), 
    Amount: new NumericQueryColumn<number>("Invoice.Amount",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Decimal,
        ""
    )
), 
    Paid: new QueryColumn<boolean | null>("Invoice.Paid",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Bool,
        ""
    )
), 
};

export const Tag = {
    Id: new IntegerQueryColumn<number>("Tag.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    TagName: new StringQueryColumn<string>("Tag.TagName",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
};

export const InvoiceTag = {
    InvoiceId: new IntegerQueryColumn<number>("InvoiceTag.InvoiceId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Invoice.Id"
    )
), 
    TagId: new IntegerQueryColumn<number>("InvoiceTag.TagId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Tag.Id"
    )
), 
};

export const Category = {
    Id: new IntegerQueryColumn<number>("Category.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    CategoryName: new StringQueryColumn<string>("Category.CategoryName",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
};

export const InvoiceCategory = {
    InvoiceId: new IntegerQueryColumn<number>("InvoiceCategory.InvoiceId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Invoice.Id"
    )
), 
    CategoryId: new IntegerQueryColumn<number>("InvoiceCategory.CategoryId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Category.Id"
    )
), 
};

export const AnnotationName = {
    Id: new IntegerQueryColumn<number>("AnnotationName.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    Name: new StringQueryColumn<string>("AnnotationName.Name",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
};

export const AnnotationValue = {
    Id: new IntegerQueryColumn<number>("AnnotationValue.Id",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        ""
    )
), 
    AnnotationNameId: new IntegerQueryColumn<number>("AnnotationValue.AnnotationNameId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "AnnotationName.Id"
    )
), 
    Value: new StringQueryColumn<string>("AnnotationValue.Value",
    new QueryColumnRuntimeType(
        QueryColumnDataType.String,
        ""
    )
), 
};

export const InvoiceAnnotation = {
    InvoiceId: new IntegerQueryColumn<number>("InvoiceAnnotation.InvoiceId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "Invoice.Id"
    )
), 
    AnnotationValueId: new IntegerQueryColumn<number>("InvoiceAnnotation.AnnotationValueId",
    new QueryColumnRuntimeType(
        QueryColumnDataType.Long,
        "AnnotationValue.Id"
    )
), 
};

export const TestSchema = {
    Department,
    Vendor,
    Invoice,
    Tag,
    InvoiceTag,
    Category,
    InvoiceCategory,
    AnnotationName,
    AnnotationValue,
    InvoiceAnnotation,
};
export const yaml = `
    schema: TestSchema
    name: Testing
    tables:
    
        Department:
            id:
                Id: [long]
            columns:
                DepartmentName: [string]
    
        Vendor:
            name: Supplier
            id:
                Id: [long]
            columns:
                VendorName: [string]
                DepartmentId: [Department]
    
        Invoice:
            id:
                Id: [long]
            columns:
                VendorId: [Vendor]
                DepartmentId: [Department]
                Amount: [decimal, FancyAmount]
                Paid: [bool?]
    
        Tag:
            id:
                Id: [long]
            columns:
                TagName: [string]
    
        InvoiceTag:
            columns:
                InvoiceId: [Invoice]
                TagId: [Tag]
    
        Category:
            id:
                Id: [long]
            columns:
                CategoryName: [string]
    
        InvoiceCategory:
            columns:
                InvoiceId: [Invoice]
                CategoryId: [Category]
    
        AnnotationName:
            conjoint: true
            id:
                Id: [long]
            columns:
                Name: [string]
    
        AnnotationValue:
            conjoint: true
            id:
                Id: [long]
            columns:
                AnnotationNameId: [AnnotationName]
                Value: [string]
    
        InvoiceAnnotation:
            conjoint: true
            associative: [InvoiceId, AnnotationValueId]
            columns:
                InvoiceId: [Invoice]
                AnnotationValueId: [AnnotationValue]
    
    `;    
""".Trim()
            );

        console
            .ToString()
            .Should()
            .Be(
                @"Exporting table Department
Exporting table Vendor
Exporting table Invoice
Exporting table Tag
Exporting table InvoiceTag
Exporting table Category
Exporting table InvoiceCategory
Exporting table AnnotationName
Exporting table AnnotationValue
Exporting table InvoiceAnnotation
Done.
"
            );
    }

    [Fact]
    public void GeneratesCSharpFromYaml()
    {
        var yaml = ExecutionTests.FindSchemaText("testSchema");

        var writer = new StringWriter();
        var console = new StringWriter();
        CSharp.FromYamlText(yaml, "FlowerBI.Engine.Tests", writer, console);

        writer
            .ToString()
            .Trim()
            .Should()
            .Be(
                $$""""
                #nullable enable
                namespace FlowerBI.Engine.Tests;


                // Important: this file is auto-generated by flowerbi.

                public static class TestSchema
                {
                    public const string Name = "TestSchema";
                    public static class Department
                    {
                        public const string Name = "Department";
                        public const string Id = "Department.Id";
                        public const string DepartmentName = "Department.DepartmentName";
                    }
                    public static class Vendor
                    {
                        public const string Name = "Vendor";
                        public const string Id = "Vendor.Id";
                        public const string VendorName = "Vendor.VendorName";
                        public const string DepartmentId = "Vendor.DepartmentId";
                    }
                    public static class Invoice
                    {
                        public const string Name = "Invoice";
                        public const string Id = "Invoice.Id";
                        public const string VendorId = "Invoice.VendorId";
                        public const string DepartmentId = "Invoice.DepartmentId";
                        public const string Amount = "Invoice.Amount";
                        public const string Paid = "Invoice.Paid";
                    }
                    public static class Tag
                    {
                        public const string Name = "Tag";
                        public const string Id = "Tag.Id";
                        public const string TagName = "Tag.TagName";
                    }
                    public static class InvoiceTag
                    {
                        public const string Name = "InvoiceTag";
                        public const string InvoiceId = "InvoiceTag.InvoiceId";
                        public const string TagId = "InvoiceTag.TagId";
                    }
                    public static class Category
                    {
                        public const string Name = "Category";
                        public const string Id = "Category.Id";
                        public const string CategoryName = "Category.CategoryName";
                    }
                    public static class InvoiceCategory
                    {
                        public const string Name = "InvoiceCategory";
                        public const string InvoiceId = "InvoiceCategory.InvoiceId";
                        public const string CategoryId = "InvoiceCategory.CategoryId";
                    }
                    public static class AnnotationName
                    {
                        public const string Name = "AnnotationName";
                        public const string Id = "AnnotationName.Id";
                        public const string Name = "AnnotationName.Name";
                    }
                    public static class AnnotationValue
                    {
                        public const string Name = "AnnotationValue";
                        public const string Id = "AnnotationValue.Id";
                        public const string AnnotationNameId = "AnnotationValue.AnnotationNameId";
                        public const string Value = "AnnotationValue.Value";
                    }
                    public static class InvoiceAnnotation
                    {
                        public const string Name = "InvoiceAnnotation";
                        public const string InvoiceId = "InvoiceAnnotation.InvoiceId";
                        public const string AnnotationValueId = "InvoiceAnnotation.AnnotationValueId";
                    }
                    
                    public const string Yaml = """
                        schema: TestSchema
                        name: Testing
                        tables:
                        
                            Department:
                                id:
                                    Id: [long]
                                columns:
                                    DepartmentName: [string]
                        
                            Vendor:
                                name: Supplier
                                id:
                                    Id: [long]
                                columns:
                                    VendorName: [string]
                                    DepartmentId: [Department]
                        
                            Invoice:
                                id:
                                    Id: [long]
                                columns:
                                    VendorId: [Vendor]
                                    DepartmentId: [Department]
                                    Amount: [decimal, FancyAmount]
                                    Paid: [bool?]
                        
                            Tag:
                                id:
                                    Id: [long]
                                columns:
                                    TagName: [string]
                        
                            InvoiceTag:
                                columns:
                                    InvoiceId: [Invoice]
                                    TagId: [Tag]
                        
                            Category:
                                id:
                                    Id: [long]
                                columns:
                                    CategoryName: [string]
                        
                            InvoiceCategory:
                                columns:
                                    InvoiceId: [Invoice]
                                    CategoryId: [Category]
                        
                            AnnotationName:
                                conjoint: true
                                id:
                                    Id: [long]
                                columns:
                                    Name: [string]
                        
                            AnnotationValue:
                                conjoint: true
                                id:
                                    Id: [long]
                                columns:
                                    AnnotationNameId: [AnnotationName]
                                    Value: [string]
                        
                            InvoiceAnnotation:
                                conjoint: true
                                associative: [InvoiceId, AnnotationValueId]
                                columns:
                                    InvoiceId: [Invoice]
                                    AnnotationValueId: [AnnotationValue]
                        
                        """;
                }
                """".Trim()
            );

        console
            .ToString()
            .Should()
            .Be(
                @"Exporting table Department
Exporting table Vendor
Exporting table Invoice
Exporting table Tag
Exporting table InvoiceTag
Exporting table Category
Exporting table InvoiceCategory
Exporting table AnnotationName
Exporting table AnnotationValue
Exporting table InvoiceAnnotation
Done.
"
            );
    }
}
