import { ResolvedSchema, ResolvedColumn, DataType } from '../schema/YamlSchemaTypes';
import { SchemaResolver } from '../schema/SchemaResolver';
import { IndentedWriter } from './IndentedWriter';

/**
 * Generates C# code from YAML schema definitions
 * Equivalent to the C# CSharp.cs generator
 */
export class CSharpGenerator {
  
  /**
   * Convert DataType to C# type string
   */
  private static getCSharpType(dataType: DataType, nullable: boolean): string {
    let csType: string;
    
    switch (dataType) {
      case DataType.Bool:
        csType = 'bool';
        break;
      case DataType.Byte:
        csType = 'byte';
        break;
      case DataType.Short:
        csType = 'short';
        break;
      case DataType.Int:
        csType = 'int';
        break;
      case DataType.Long:
        csType = 'long';
        break;
      case DataType.Float:
        csType = 'float';
        break;
      case DataType.Double:
        csType = 'double';
        break;
      case DataType.Decimal:
        csType = 'decimal';
        break;
      case DataType.String:
        csType = 'string';
        break;
      case DataType.DateTime:
        csType = 'DateTime';
        break;
      default:
        throw new Error(`Unsupported data type: ${dataType}`);
    }

    return nullable ? `${csType}?` : csType;
  }

  /**
   * Generate C# code from YAML schema text
   */
  static fromYaml(
    yamlText: string, 
    csNamespace: string
  ): { code: string; console: string } {
    const consoleOutput: string[] = [];
    
    try {
      const schema = SchemaResolver.resolve(yamlText);
      const code = CSharpGenerator.fromSchema(schema, yamlText, csNamespace, consoleOutput);
      
      return {
        code,
        console: consoleOutput.join('\n')
      };
    } catch (error) {
      consoleOutput.push(`Error: ${error instanceof Error ? error.message : String(error)}`);
      return {
        code: '',
        console: consoleOutput.join('\n')
      };
    }
  }

  /**
   * Generate C# code from a resolved schema
   */
  private static fromSchema(
    schema: ResolvedSchema,
    yamlText: string,
    csNamespace: string,
    consoleOutput: string[]
  ): string {
    const output: string[] = [];
    const writer = new IndentedWriter();
    
    // Header
    output.push('#nullable enable');
    output.push(`namespace ${csNamespace};`);
    output.push('');
    output.push('');
    output.push('// Important: this file is auto-generated by flowerbi.');
    output.push('');

    // Schema class
    output.push(`public static class ${schema.Name}`);
    output.push('{');

    // Schema name constant
    writer.writeLine(`public const string Name = "${schema.Name}";`);
    output.push(writer.toString());
    writer.clear();

    // Generate table classes
    for (const table of schema.Tables) {
      consoleOutput.push(`Exporting table ${table.Name}`);

      writer.writeLine(`public static class ${table.Name}`);
      writer.writeLine('{');
      output.push(writer.toString());
      writer.clear();

      const tableWriter = new IndentedWriter(8); // Double indent for nested class

      // Table name constant
      tableWriter.writeLine(`public const string Name = "${table.Name}";`);

      // Helper function to write column constants
      const writeColumn = (column: ResolvedColumn) => {
        tableWriter.writeLine(
          `public const string ${column.Name} = "${column.Table.Name}.${column.Name}";`
        );
      };

      // Write ID column if exists
      if (table.IdColumn) {
        writeColumn(table.IdColumn);
      }

      // Write regular columns
      for (const column of table.Columns) {
        writeColumn(column);
      }

      output.push(tableWriter.toString());
      tableWriter.clear();

      writer.writeLine('}');
      output.push(writer.toString());
      writer.clear();
    }

    output.push('');

    // Generate YAML constant
    writer.writeLine('public const string Yaml = """');
    
    const yamlLines = yamlText.split('\n');
    for (const line of yamlLines) {
      writer.writeLine(line.trimEnd());
    }
    
    writer.writeLine('""";');
    output.push(writer.toString());
    writer.clear();

    // Close schema class
    output.push('}');

    consoleOutput.push('Done.');
    
    return output.join('\n');
  }

  /**
   * Generate C# code from YAML file content
   */
  static fromYamlFile(yamlText: string, csNamespace: string): string {
    const result = CSharpGenerator.fromYaml(yamlText, csNamespace);
    return result.code;
  }
}