import { TypeScriptGenerator, CSharpGenerator } from '@flowerbi/query-generation';
import { ExecutionTestsBase } from './ExecutionTestsBase';

describe('Code Generation', () => {
  const yamlSchema = ExecutionTestsBase.findSchemaText('testSchema');

  test('TypeScript generator produces valid code', () => {
    const result = TypeScriptGenerator.fromYaml(yamlSchema);
    
    expect(result.code).toBeTruthy();
    expect(result.console).toContain('Done.');
    
    // Should contain imports
    expect(result.code).toContain('import {');
    expect(result.code).toContain('@flowerbi/client');
    
    // Should contain table exports
    expect(result.code).toContain('export const Vendor = {');
    expect(result.code).toContain('export const Invoice = {');
    
    // Should contain column definitions
    expect(result.code).toContain('VendorName: new StringQueryColumn');
    expect(result.code).toContain('Amount: new NumericQueryColumn');
    
    // Should contain schema export
    expect(result.code).toContain('export const TestSchema = {');
    
    // Should contain YAML export
    expect(result.code).toContain('export const yaml = `');
  });

  test('C# generator produces valid code', () => {
    const result = CSharpGenerator.fromYaml(yamlSchema, 'MyApp.Schema');
    
    expect(result.code).toBeTruthy();
    expect(result.console).toContain('Done.');
    
    // Should contain namespace
    expect(result.code).toContain('namespace MyApp.Schema;');
    
    // Should contain nullable enable
    expect(result.code).toContain('#nullable enable');
    
    // Should contain auto-generated comment
    expect(result.code).toContain('auto-generated by flowerbi');
    
    // Should contain schema class
    expect(result.code).toContain('public static class TestSchema');
    
    // Should contain table classes
    expect(result.code).toContain('public static class Vendor');
    expect(result.code).toContain('public static class Invoice');
    
    // Should contain column constants
    expect(result.code).toContain('public const string VendorName = "Vendor.VendorName";');
    expect(result.code).toContain('public const string Amount = "Invoice.Amount";');
    
    // Should contain YAML constant
    expect(result.code).toContain('public const string Yaml = """');
  });

  test('TypeScript generator handles different data types', () => {
    const simpleSchema = `
schema: SimpleSchema
tables:
  TestTable:
    id:
      Id: [int]
    columns:
      Name: [string]
      IsActive: [bool]
      CreatedDate: [datetime]
      Price: [decimal]
      Count: [int]
`;

    const result = TypeScriptGenerator.fromYaml(simpleSchema);
    
    // Check type mappings
    expect(result.code).toContain('Name: new StringQueryColumn<string>');
    expect(result.code).toContain('IsActive: new QueryColumn<boolean>');
    expect(result.code).toContain('CreatedDate: new QueryColumn<Date>');
    expect(result.code).toContain('Price: new NumericQueryColumn<number>');
    expect(result.code).toContain('Count: new IntegerQueryColumn<number>');
  });

  test('C# generator handles different data types', () => {
    const simpleSchema = `
schema: SimpleSchema
tables:
  TestTable:
    id:
      Id: [int]
    columns:
      Name: [string]
      IsActive: [bool]
      CreatedDate: [datetime]
      Price: [decimal]
      Count: [int]
      OptionalField: [string?]
`;

    const result = CSharpGenerator.fromYaml(simpleSchema, 'Test.Schema');
    
    // All columns should be present as constants
    expect(result.code).toContain('public const string Id = "TestTable.Id";');
    expect(result.code).toContain('public const string Name = "TestTable.Name";');
    expect(result.code).toContain('public const string IsActive = "TestTable.IsActive";');
    expect(result.code).toContain('public const string CreatedDate = "TestTable.CreatedDate";');
    expect(result.code).toContain('public const string Price = "TestTable.Price";');
    expect(result.code).toContain('public const string Count = "TestTable.Count";');
    expect(result.code).toContain('public const string OptionalField = "TestTable.OptionalField";');
  });

  test('Generators handle foreign key relationships', () => {
    const schemaWithFK = `
schema: FKSchema
tables:
  User:
    id:
      Id: [int]
    columns:
      Name: [string]
  Order:
    id:
      Id: [int]
    columns:
      UserId: [User]
      Total: [decimal]
`;

    const tsResult = TypeScriptGenerator.fromYaml(schemaWithFK);
    const csResult = CSharpGenerator.fromYaml(schemaWithFK, 'FK.Schema');
    
    // TypeScript should include target information
    expect(tsResult.code).toContain('UserId: new IntegerQueryColumn');
    expect(tsResult.code).toContain('"User.Id"');
    
    // C# should include the foreign key column
    expect(csResult.code).toContain('public const string UserId = "Order.UserId";');
  });

  test('Generators preserve YAML content', () => {
    const originalYaml = `
schema: TestSchema
name: test
tables:
  SimpleTable:
    id:
      Id: [int]
    columns:
      Name: [string]
`.trim();

    const tsResult = TypeScriptGenerator.fromYaml(originalYaml);
    const csResult = CSharpGenerator.fromYaml(originalYaml, 'Test');
    
    // Both should preserve the original YAML content (check key parts)
    expect(tsResult.code).toContain('export const yaml = `');
    expect(tsResult.code).toContain('schema: TestSchema');
    expect(tsResult.code).toContain('SimpleTable:');
    
    expect(csResult.code).toContain('public const string Yaml = """');
    expect(csResult.code).toContain('schema: TestSchema');
    expect(csResult.code).toContain('SimpleTable:');
  });
});