using System.IO;
using FlowerBI.Yaml;

namespace FlowerBI.Conversion;

public static class CSharp
{
    public static string CSColumnType(DataType dataType, bool nullable)
    {
        var csType = dataType switch
        {
            DataType.Bool => "bool",
            DataType.Byte => "byte",
            DataType.Short => "short",
            DataType.Int => "int",
            DataType.Long => "long",
            DataType.Float => "float",
            DataType.Double => "double",
            DataType.Decimal => "decimal",
            DataType.String => "string",
            DataType.DateTime => "DateTime",
            _ => throw new FlowerBIException($"Unsupported data type: {dataType}"),
        };

        return nullable ? $"{csType}?" : csType;
    }

    public static void FromYaml(
        string yamlFile,
        string csFile,
        string csNamespace,
        TextWriter console
    )
    {
        using var writer = new WriteIfDifferent(csFile, console);

        FromYamlText(File.ReadAllText(yamlFile), csNamespace, writer.Output, writer.Console);
    }

    public static void FromYamlText(
        string yamlText,
        string csNamespace,
        TextWriter writer,
        TextWriter console
    )
    {
        var schema = ResolvedSchema.Resolve(yamlText);

        writer.WriteLine("#nullable enable");
        writer.WriteLine($"namespace {csNamespace};");
        writer.WriteLine();
        writer.WriteLine();
        writer.WriteLine("// Important: this file is auto-generated by flowerbi.");
        writer.WriteLine();

        writer.WriteLine($"public static class {schema.Name}");
        writer.WriteLine("{");

        var schemaWriter = new IndentedWriter(writer);

        schemaWriter.WriteLine(
            $"""
            public const string _TableName = "{schema.Name}";
            """
        );

        foreach (var table in schema.Tables)
        {
            console.WriteLine($"Exporting table {table.Name}");

            schemaWriter.WriteLine($"public static class {table.Name}");
            schemaWriter.WriteLine("{");

            var tableWriter = new IndentedWriter(schemaWriter);

            tableWriter.WriteLine(
                $"""
                public const string Name = "{table.Name}";
                """
            );

            void WriteColumn(ResolvedColumn column)
            {
                tableWriter.WriteLine(
                    $"""
                    public const string {column.Name} = "{column.Table.Name}.{column.Name}";
                    """
                );
            }

            if (table.IdColumn != null)
            {
                WriteColumn(table.IdColumn);
            }

            foreach (var column in table.Columns)
            {
                WriteColumn(column);
            }

            schemaWriter.WriteLine("}");
        }

        schemaWriter.WriteLine(string.Empty);

        schemaWriter.WriteLine("public const string Yaml = \"\"\"");

        var yamlWriter = new IndentedWriter(schemaWriter);
        foreach (var line in yamlText.Split('\n'))
        {
            yamlWriter.WriteLine(line.TrimEnd());
        }
        yamlWriter.WriteLine("\"\"\";");

        writer.WriteLine("}");

        writer.Flush();
        console.WriteLine("Done.");
    }
}
