import { QueryColumn } from "flowerbi";

// Important: this file is auto-generated by flowerbi.

export const DateReported = {
    Id: new QueryColumn<Date>("DateReported.Id"),
    CalendarYearNumber: new QueryColumn<number>("DateReported.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateReported.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateReported.FirstDayOfMonth"),
};

export const DateResolved = {
    Id: new QueryColumn<Date>("DateResolved.Id"),
    CalendarYearNumber: new QueryColumn<number>("DateResolved.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateResolved.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateResolved.FirstDayOfMonth"),
};

export const DateAssigned = {
    Id: new QueryColumn<Date>("DateAssigned.Id"),
    CalendarYearNumber: new QueryColumn<number>("DateAssigned.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateAssigned.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateAssigned.FirstDayOfMonth"),
};

export const Workflow = {
    Id: new QueryColumn<number>("Workflow.Id"),
    Resolved: new QueryColumn<boolean>("Workflow.Resolved"),
    WorkflowState: new QueryColumn<string>("Workflow.WorkflowState"),
    SourceOfError: new QueryColumn<string>("Workflow.SourceOfError"),
    FixedByCustomer: new QueryColumn<boolean>("Workflow.FixedByCustomer"),
};

export const Category = {
    Id: new QueryColumn<number>("Category.Id"),
    Label: new QueryColumn<string>("Category.Label"),
};

export const Customer = {
    Id: new QueryColumn<number>("Customer.Id"),
    CustomerName: new QueryColumn<string>("Customer.CustomerName"),
};

export const CoderAssigned = {
    Id: new QueryColumn<number>("CoderAssigned.Id"),
    FullName: new QueryColumn<string>("CoderAssigned.FullName"),
};

export const CoderResolved = {
    Id: new QueryColumn<number>("CoderResolved.Id"),
    FullName: new QueryColumn<string>("CoderResolved.FullName"),
};

export const CategoryCombination = {
    Id: new QueryColumn<number>("CategoryCombination.Id"),
    Crashed: new QueryColumn<boolean>("CategoryCombination.Crashed"),
    DataLoss: new QueryColumn<boolean>("CategoryCombination.DataLoss"),
    SecurityBreach: new QueryColumn<boolean>("CategoryCombination.SecurityBreach"),
    OffByOne: new QueryColumn<boolean>("CategoryCombination.OffByOne"),
    Slow: new QueryColumn<boolean>("CategoryCombination.Slow"),
    StackOverflow: new QueryColumn<boolean>("CategoryCombination.StackOverflow"),
};

export const Bug = {
    Id: new QueryColumn<number>("Bug.Id"),
    WorkflowId: new QueryColumn<number>("Bug.WorkflowId"),
    CustomerId: new QueryColumn<number>("Bug.CustomerId"),
    ReportedDate: new QueryColumn<Date>("Bug.ReportedDate"),
    ResolvedDate: new QueryColumn<Date>("Bug.ResolvedDate"),
    AssignedDate: new QueryColumn<Date>("Bug.AssignedDate"),
    CategoryCombinationId: new QueryColumn<number>("Bug.CategoryCombinationId"),
    AssignedCoderId: new QueryColumn<number>("Bug.AssignedCoderId"),
    ResolvedCoderId: new QueryColumn<number>("Bug.ResolvedCoderId"),
};

export const NxgSchema = {
    Tables: [
        {
            id: "DateReported",
            ref: DateReported,
            columns: [
                {
                    id: "DateReported.Id",
                    ref: DateReported.Id,
                },
                {
                    id: "DateReported.CalendarYearNumber",
                    ref: DateReported.CalendarYearNumber,
                },
                {
                    id: "DateReported.FirstDayOfQuarter",
                    ref: DateReported.FirstDayOfQuarter,
                },
                {
                    id: "DateReported.FirstDayOfMonth",
                    ref: DateReported.FirstDayOfMonth,
                },
            ],
        },
        {
            id: "DateResolved",
            ref: DateResolved,
            columns: [
                {
                    id: "DateResolved.Id",
                    ref: DateResolved.Id,
                },
                {
                    id: "DateResolved.CalendarYearNumber",
                    ref: DateResolved.CalendarYearNumber,
                },
                {
                    id: "DateResolved.FirstDayOfQuarter",
                    ref: DateResolved.FirstDayOfQuarter,
                },
                {
                    id: "DateResolved.FirstDayOfMonth",
                    ref: DateResolved.FirstDayOfMonth,
                },
            ],
        },
        {
            id: "DateAssigned",
            ref: DateAssigned,
            columns: [
                {
                    id: "DateAssigned.Id",
                    ref: DateAssigned.Id,
                },
                {
                    id: "DateAssigned.CalendarYearNumber",
                    ref: DateAssigned.CalendarYearNumber,
                },
                {
                    id: "DateAssigned.FirstDayOfQuarter",
                    ref: DateAssigned.FirstDayOfQuarter,
                },
                {
                    id: "DateAssigned.FirstDayOfMonth",
                    ref: DateAssigned.FirstDayOfMonth,
                },
            ],
        },
        {
            id: "Workflow",
            ref: Workflow,
            columns: [
                {
                    id: "Workflow.Id",
                    ref: Workflow.Id,
                },
                {
                    id: "Workflow.Resolved",
                    ref: Workflow.Resolved,
                },
                {
                    id: "Workflow.WorkflowState",
                    ref: Workflow.WorkflowState,
                },
                {
                    id: "Workflow.SourceOfError",
                    ref: Workflow.SourceOfError,
                },
                {
                    id: "Workflow.FixedByCustomer",
                    ref: Workflow.FixedByCustomer,
                },
            ],
        },
        {
            id: "Category",
            ref: Category,
            columns: [
                {
                    id: "Category.Id",
                    ref: Category.Id,
                },
                {
                    id: "Category.Label",
                    ref: Category.Label,
                },
            ],
        },
        {
            id: "Customer",
            ref: Customer,
            columns: [
                {
                    id: "Customer.Id",
                    ref: Customer.Id,
                },
                {
                    id: "Customer.CustomerName",
                    ref: Customer.CustomerName,
                },
            ],
        },
        {
            id: "CoderAssigned",
            ref: CoderAssigned,
            columns: [
                {
                    id: "CoderAssigned.Id",
                    ref: CoderAssigned.Id,
                },
                {
                    id: "CoderAssigned.FullName",
                    ref: CoderAssigned.FullName,
                },
            ],
        },
        {
            id: "CoderResolved",
            ref: CoderResolved,
            columns: [
                {
                    id: "CoderResolved.Id",
                    ref: CoderResolved.Id,
                },
                {
                    id: "CoderResolved.FullName",
                    ref: CoderResolved.FullName,
                },
            ],
        },
        {
            id: "CategoryCombination",
            ref: CategoryCombination,
            columns: [
                {
                    id: "CategoryCombination.Id",
                    ref: CategoryCombination.Id,
                },
                {
                    id: "CategoryCombination.Crashed",
                    ref: CategoryCombination.Crashed,
                },
                {
                    id: "CategoryCombination.DataLoss",
                    ref: CategoryCombination.DataLoss,
                },
                {
                    id: "CategoryCombination.SecurityBreach",
                    ref: CategoryCombination.SecurityBreach,
                },
                {
                    id: "CategoryCombination.OffByOne",
                    ref: CategoryCombination.OffByOne,
                },
                {
                    id: "CategoryCombination.Slow",
                    ref: CategoryCombination.Slow,
                },
                {
                    id: "CategoryCombination.StackOverflow",
                    ref: CategoryCombination.StackOverflow,
                },
            ],
        },
        {
            id: "Bug",
            ref: Bug,
            columns: [
                {
                    id: "Bug.Id",
                    ref: Bug.Id,
                },
                {
                    id: "Bug.WorkflowId",
                    ref: Bug.WorkflowId,
                },
                {
                    id: "Bug.CustomerId",
                    ref: Bug.CustomerId,
                },
                {
                    id: "Bug.ReportedDate",
                    ref: Bug.ReportedDate,
                },
                {
                    id: "Bug.ResolvedDate",
                    ref: Bug.ResolvedDate,
                },
                {
                    id: "Bug.AssignedDate",
                    ref: Bug.AssignedDate,
                },
                {
                    id: "Bug.CategoryCombinationId",
                    ref: Bug.CategoryCombinationId,
                },
                {
                    id: "Bug.AssignedCoderId",
                    ref: Bug.AssignedCoderId,
                },
                {
                    id: "Bug.ResolvedCoderId",
                    ref: Bug.ResolvedCoderId,
                },
            ],
        },
    ],
};
