import { QueryColumn, NumericQueryColumn } from "flowerbi";

// Important: this file is auto-generated by flowerbi.

export const Date = {
    Id: new QueryColumn<Date>("Date.Id"),
    CalendarYearNumber: new NumericQueryColumn<number>("Date.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("Date.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("Date.FirstDayOfMonth"),
};

export const DateReported = {
    Id: new QueryColumn<Date>("DateReported.Id"),
    CalendarYearNumber: new NumericQueryColumn<number>("DateReported.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateReported.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateReported.FirstDayOfMonth"),
};

export const DateResolved = {
    Id: new QueryColumn<Date>("DateResolved.Id"),
    CalendarYearNumber: new NumericQueryColumn<number>("DateResolved.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateResolved.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateResolved.FirstDayOfMonth"),
};

export const DateAssigned = {
    Id: new QueryColumn<Date>("DateAssigned.Id"),
    CalendarYearNumber: new NumericQueryColumn<number>("DateAssigned.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateAssigned.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateAssigned.FirstDayOfMonth"),
};

export const Workflow = {
    Id: new NumericQueryColumn<number>("Workflow.Id"),
    Resolved: new QueryColumn<boolean>("Workflow.Resolved"),
    WorkflowState: new QueryColumn<string>("Workflow.WorkflowState"),
    SourceOfError: new QueryColumn<string>("Workflow.SourceOfError"),
    FixedByCustomer: new QueryColumn<boolean>("Workflow.FixedByCustomer"),
};

export const Category = {
    Id: new NumericQueryColumn<number>("Category.Id"),
    Label: new QueryColumn<string>("Category.Label"),
};

export const Customer = {
    Id: new NumericQueryColumn<number>("Customer.Id"),
    CustomerName: new QueryColumn<string>("Customer.CustomerName"),
};

export const Coder = {
    Id: new NumericQueryColumn<number>("Coder.Id"),
    FullName: new QueryColumn<string>("Coder.FullName"),
};

export const CoderAssigned = {
    Id: new NumericQueryColumn<number>("CoderAssigned.Id"),
    FullName: new QueryColumn<string>("CoderAssigned.FullName"),
};

export const CoderResolved = {
    Id: new NumericQueryColumn<number>("CoderResolved.Id"),
    FullName: new QueryColumn<string>("CoderResolved.FullName"),
};

export const CategoryCombination = {
    Id: new NumericQueryColumn<number>("CategoryCombination.Id"),
    Crashed: new QueryColumn<boolean>("CategoryCombination.Crashed"),
    DataLoss: new QueryColumn<boolean>("CategoryCombination.DataLoss"),
    SecurityBreach: new QueryColumn<boolean>("CategoryCombination.SecurityBreach"),
    OffByOne: new QueryColumn<boolean>("CategoryCombination.OffByOne"),
    Slow: new QueryColumn<boolean>("CategoryCombination.Slow"),
    StackOverflow: new QueryColumn<boolean>("CategoryCombination.StackOverflow"),
};

export const Bug = {
    Id: new NumericQueryColumn<number>("Bug.Id"),
    WorkflowId: new NumericQueryColumn<number>("Bug.WorkflowId"),
    CustomerId: new NumericQueryColumn<number>("Bug.CustomerId"),
    ReportedDate: new QueryColumn<Date>("Bug.ReportedDate"),
    ResolvedDate: new QueryColumn<Date>("Bug.ResolvedDate"),
    AssignedDate: new QueryColumn<Date>("Bug.AssignedDate"),
    CategoryCombinationId: new NumericQueryColumn<number>("Bug.CategoryCombinationId"),
    AssignedCoderId: new NumericQueryColumn<number>("Bug.AssignedCoderId"),
    ResolvedCoderId: new NumericQueryColumn<number>("Bug.ResolvedCoderId"),
};

export const BugSchema = {
    Date,
    DateReported,
    DateResolved,
    DateAssigned,
    Workflow,
    Category,
    Customer,
    Coder,
    CoderAssigned,
    CoderResolved,
    CategoryCombination,
    Bug,
};
