import { QueryColumn, NumericQueryColumn } from "flowerbi";

// Important: this file is auto-generated by flowerbi.

export const DateReported = {
    Id: new QueryColumn<Date>("DateReported.Id"),
    CalendarYearNumber: new NumericQueryColumn("DateReported.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateReported.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateReported.FirstDayOfMonth"),
};

export const DateResolved = {
    Id: new QueryColumn<Date>("DateResolved.Id"),
    CalendarYearNumber: new NumericQueryColumn("DateResolved.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateResolved.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateResolved.FirstDayOfMonth"),
};

export const DateAssigned = {
    Id: new QueryColumn<Date>("DateAssigned.Id"),
    CalendarYearNumber: new NumericQueryColumn("DateAssigned.CalendarYearNumber"),
    FirstDayOfQuarter: new QueryColumn<Date>("DateAssigned.FirstDayOfQuarter"),
    FirstDayOfMonth: new QueryColumn<Date>("DateAssigned.FirstDayOfMonth"),
};

export const Workflow = {
    Id: new NumericQueryColumn("Workflow.Id"),
    Resolved: new QueryColumn<boolean>("Workflow.Resolved"),
    WorkflowState: new QueryColumn<string>("Workflow.WorkflowState"),
    SourceOfError: new QueryColumn<string>("Workflow.SourceOfError"),
    FixedByCustomer: new QueryColumn<boolean>("Workflow.FixedByCustomer"),
};

export const Category = {
    Id: new NumericQueryColumn("Category.Id"),
    Label: new QueryColumn<string>("Category.Label"),
};

export const Customer = {
    Id: new NumericQueryColumn("Customer.Id"),
    CustomerName: new QueryColumn<string>("Customer.CustomerName"),
};

export const CoderAssigned = {
    Id: new NumericQueryColumn("CoderAssigned.Id"),
    FullName: new QueryColumn<string>("CoderAssigned.FullName"),
};

export const CoderResolved = {
    Id: new NumericQueryColumn("CoderResolved.Id"),
    FullName: new QueryColumn<string>("CoderResolved.FullName"),
};

export const CategoryCombination = {
    Id: new NumericQueryColumn("CategoryCombination.Id"),
    Crashed: new QueryColumn<boolean>("CategoryCombination.Crashed"),
    DataLoss: new QueryColumn<boolean>("CategoryCombination.DataLoss"),
    SecurityBreach: new QueryColumn<boolean>("CategoryCombination.SecurityBreach"),
    OffByOne: new QueryColumn<boolean>("CategoryCombination.OffByOne"),
    Slow: new QueryColumn<boolean>("CategoryCombination.Slow"),
    StackOverflow: new QueryColumn<boolean>("CategoryCombination.StackOverflow"),
};

export const Bug = {
    Id: new NumericQueryColumn("Bug.Id"),
    WorkflowId: new NumericQueryColumn("Bug.WorkflowId"),
    CustomerId: new NumericQueryColumn("Bug.CustomerId"),
    ReportedDate: new QueryColumn<Date>("Bug.ReportedDate"),
    ResolvedDate: new QueryColumn<Date>("Bug.ResolvedDate"),
    AssignedDate: new QueryColumn<Date>("Bug.AssignedDate"),
    CategoryCombinationId: new NumericQueryColumn("Bug.CategoryCombinationId"),
    AssignedCoderId: new NumericQueryColumn("Bug.AssignedCoderId"),
    ResolvedCoderId: new NumericQueryColumn("Bug.ResolvedCoderId"),
};

export const BugSchema = {
    DateReported,
    DateResolved,
    DateAssigned,
    Workflow,
    Category,
    Customer,
    CoderAssigned,
    CoderResolved,
    CategoryCombination,
    Bug,
};
